[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

#[font]
#normal = { family = "Hack Nerd Font Mono", style = "Bold" }
#bold = { family = "Hack Nerd Font Mono", style = "Bold" }
#italic = { family = "Hack Nerd Font Mono", style = "Italic" }
#bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
#size = 7
[font]
size = 7.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Bold"

[window]
dimensions = { columns = 160, lines = 60  }
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
decorations = "Full"
dynamic_title = false
#dynamic_padding = false
blur = true

[scrolling]
history = 99999

[colors]

[cursor]
vi_mode_style = {shape = "Block", blinking = "On"}

[selection]
save_to_clipboard = true


[general]
live_config_reload = true

import = [
  "~/.config/alacritty/colour/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/colour/alacritty/ccatppuccin-frappe.toml"
  # "~/.config/alacritty/colour/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/colour/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"



